# vim: set sts=4 sw=4 et :

Import("env")

env.Command(
    ["engine_version.h"],
    [],
    ["echo '#define ENGINE_VERSION \"$ENGINE_VERSION\"' >$TARGET"],
)

env.Program(
    "orionsfurnace",
    [
        env.Glob("*.cpp"),
        env.Glob("core/*.cpp"),
        env.Glob("gfx/*.cpp"),
        env.Glob("loops/*.cpp"),
        env.Glob("net/*.cpp"),
    ],
    CPPPATH = [
        env.Dir("."),
        env.Dir(".").srcnode(),
        env["CPPPATH"],
    ]
)
